import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";
import { CloudDownload, Download } from "lucide-react";
import Link from "next/link";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col h-screen`}
      >
        <div className="flex items-center justify-center h-14">
          <div className="flex flex-row items-center justify-between w-3/5">
            <div className="flex flex-row items-center justify-center gap-1">
              <Avatar>
                <AvatarImage
                  src="https://media.licdn.com/dms/image/v2/D4E03AQG1-FX5D-Y4Eg/profile-displayphoto-shrink_400_400/B4EZczZODqH8Ag-/0/1748913939468?e=1754524800&v=beta&t=jHcXhGq_y4mLX_jISVuo7LBstAMliaTttbqxRPXrksI"
                  alt="@shadcn"
                />
                <AvatarFallback>CN</AvatarFallback>
              </Avatar>
              <Button
                variant="ghost"
                className="text-xl font-semibold tracking-tight"
                asChild
              >
                <Link href={"/"}>Magnus Reeves</Link>
              </Button>
              <Button
                variant="ghost"
                className="text-xl font-normal tracking-tight"
                asChild
              >
                <Link href={"/about"}>about</Link>
              </Button>
              <Button
                variant="ghost"
                className="text-xl font-normal tracking-tight"
                asChild
              >
                <Link href={"/projects"}>projects</Link>
              </Button>
              <Button
                variant="ghost"
                className="text-xl font-normal tracking-tight"
                asChild
              >
                <Link href={"/personal"}>personal</Link>
              </Button>
              <Button
                variant="ghost"
                className="text-xl font-normal tracking-tight"
                asChild
              >
                <Link href={"/contact"}>contact</Link>
              </Button>
            </div>
            <Button
              variant="ghost"
              className="text-xl font-normal tracking-tight"
            >
              <div className="flex flex-row items-center gap-2">
                resume
                <Download />
              </div>
            </Button>
          </div>
        </div>
        <div className="flex-1 overflow-scroll">
          <div className="w-4/5 mx-auto">{children}</div>
          <footer className="w-4/5 border-t bg-background mx-auto py-4">
            <p>{new Date().getFullYear()} Magnus Reeves personal site,</p>
            <p>developed using NextJS</p>
            <p>
              <Link
                href="https://github.com/rreeves8"
                target="_blank"
                className="link"
                aria-label="GitHub repository"
              >
                View on GitHub
              </Link>
            </p>
          </footer>
        </div>
      </body>
    </html>
  );
}
